---
version: '3'
services:
  freqtrade:
      image: freqtradeorg/freqtrade:develop_freqai
      restart: unless-stopped
      container_name: strategy
      ports:
        - "127.0.0.1:8080:8080"
      volumes:
        - "./user_data:/freqtrade/user_data"
      command: >
        trade
        --logfile /freqtrade/user_data/logs/strategy.log
        --db-url sqlite:////freqtrade/user_data/db_strategy.sqlite
        --config /freqtrade/user_data/config_strategy.json
        --strategy Strategy
  
